version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            - postgres
            - redis
        env_file:
            - .env

    postgres:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_DB: weather_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"

    redis:
        image: redis:7
        ports:
            - "6379:6379"

    mailpit:
        image: axllent/mailpit
        ports:
            - "8025:8025"

