version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            - postgres
            - redis
        env_file:
            - .env

    postgres:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_DB: weather_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"

    redis:
        image: redis:7
        ports:
            - "6379:6379"

    mailpit:
        image: axllent/mailpit
        ports:
            - "8025:8025"

#version: '3.8'
#
#services:
#    app:
#        build:
#            context: .
#            dockerfile: Dockerfile
#        container_name: weather-app
#        depends_on:
#            - postgres
#        ports:
#            - "8000:8000"
#        environment:
#            DB_CONNECTION=pgsql
#            DB_HOST=postgres.railway.internal
#            DB_PORT=5432
#            DB_DATABASE=railway
#            DB_USERNAME=postgres
#            DB_PASSWORD=JyVBnoamATNtWzqLuHepveRupMeoRSNo
#
#    postgres:
#        image: postgres:13
#        container_name: weather-postgres
#        restart: always
#        environment:
#            POSTGRES_DB: railway
#            POSTGRES_USER: postgres
#            POSTGRES_PASSWORD: JyVBnoamATNtWzqLuHepveRupMeoRSNo
#        ports:
#            - "5432:5432"
#        healthcheck:
#            test: ["CMD-SHELL", "pg_isready -U postgres"]
#            interval: 10s
#            timeout: 5s
#            retries: 5
#
#    mailpit:
#        image: axllent/mailpit
#        container_name: mailpit
#        ports:
#            - "8025:8025"
